export type AreaType = {
  city: string;
  name: string;
  fullName: string;
  code: number;
  isAll?: boolean;
};

export type RegionType = AreaType & {
  subRegion?: AreaType[];
};

export const region: RegionType[] = [
  {
    city: '서울',
    name: '서울',
    fullName: '서울',
    code: 100,
    subRegion: [
      {
        city: '서울',
        name: '서울 전체',
        fullName: '서울 전체',
        code: 101,
        isAll: true,
      },
      { city: '서울', name: '강남구', fullName: '서울 강남구', code: 102 },
      { city: '서울', name: '강동구', fullName: '서울 강동구', code: 103 },
      { city: '서울', name: '강북구', fullName: '서울 강북구', code: 104 },
      { city: '서울', name: '강서구', fullName: '서울 강서구', code: 105 },
      { city: '서울', name: '관악구', fullName: '서울 관악구', code: 106 },
      { city: '서울', name: '광진구', fullName: '서울 광진구', code: 107 },
      { city: '서울', name: '구로구', fullName: '서울 구로구', code: 108 },
      { city: '서울', name: '금천구', fullName: '서울 금천구', code: 109 },
      { city: '서울', name: '노원구', fullName: '서울 노원구', code: 110 },
      { city: '서울', name: '도봉구', fullName: '서울 도봉구', code: 111 },
      { city: '서울', name: '동대문구', fullName: '서울 동대문구', code: 112 },
      { city: '서울', name: '동작구', fullName: '서울 동작구', code: 113 },
      { city: '서울', name: '마포구', fullName: '서울 마포구', code: 114 },
      { city: '서울', name: '서대문구', fullName: '서울 서대문구', code: 115 },
      { city: '서울', name: '서초구', fullName: '서울 서초구', code: 116 },
      { city: '서울', name: '성동구', fullName: '서울 성동구', code: 117 },
      { city: '서울', name: '성북구', fullName: '서울 성북구', code: 118 },
      { city: '서울', name: '송파구', fullName: '서울 송파구', code: 119 },
      { city: '서울', name: '양천구', fullName: '서울 양천구', code: 120 },
      { city: '서울', name: '영등포구', fullName: '서울 영등포구', code: 121 },
      { city: '서울', name: '용산구', fullName: '서울 용산구', code: 122 },
      { city: '서울', name: '은평구', fullName: '서울 은평구', code: 123 },
      { city: '서울', name: '종로구', fullName: '서울 종로구', code: 124 },
      { city: '서울', name: '중구', fullName: '서울 중구', code: 125 },
      { city: '서울', name: '중랑구', fullName: '서울 중랑구', code: 126 },
    ],
  },
  {
    city: '경기',
    name: '경기',
    fullName: '경기',
    code: 127,
    subRegion: [
      {
        city: '경기',
        name: '경기 전체',
        fullName: '경기 전체',
        code: 128,
        isAll: true,
      },
      { city: '경기', name: '가평군', fullName: '경기도 가평군', code: 129 },
      {
        city: '경기',
        name: '고양시 덕양구',
        fullName: '경기도 고양시 덕양구',
        code: 130,
      },
      {
        city: '경기',
        name: '고양시 일산동구',
        fullName: '경기도 고양시 일산동구',
        code: 131,
      },
      {
        city: '경기',
        name: '고양시 일산서구',
        fullName: '경기도 고양시 일산서구',
        code: 132,
      },
      { city: '경기', name: '과천시', fullName: '경기도 과천시', code: 133 },
      { city: '경기', name: '광명시', fullName: '경기도 광명시', code: 134 },
      { city: '경기', name: '광주시', fullName: '경기도 광주시', code: 135 },
      { city: '경기', name: '구리시', fullName: '경기도 구리시', code: 136 },
      { city: '경기', name: '군포시', fullName: '경기도 군포시', code: 137 },
      { city: '경기', name: '김포시', fullName: '경기도 김포시', code: 138 },
      {
        city: '경기',
        name: '남양주시',
        fullName: '경기도 남양주시',
        code: 139,
      },
      {
        city: '경기',
        name: '동두천시',
        fullName: '경기도 동두천시',
        code: 140,
      },
      { city: '경기', name: '부천시', fullName: '경기도 부천시', code: 141 },
      {
        city: '경기',
        name: '성남시 분당구',
        fullName: '경기도 성남시 분당구',
        code: 142,
      },
      {
        city: '경기',
        name: '성남시 수정구',
        fullName: '경기도 성남시 수정구',
        code: 143,
      },
      {
        city: '경기',
        name: '성남시 중원구',
        fullName: '경기도성남시 중원구',
        code: 144,
      },
      {
        city: '경기',
        name: '수원시 권선구',
        fullName: '경기도 수원시 권선구',
        code: 145,
      },
      {
        city: '경기',
        name: '수원시 영통구',
        fullName: '경기도 수원시 영통구',
        code: 146,
      },
      {
        city: '경기',
        name: '수원시 장안구',
        fullName: '경기도수원시  장안구',
        code: 147,
      },
      {
        city: '경기',
        name: '수원시 팔달구',
        fullName: '경기도 수원시 팔달구',
        code: 148,
      },
      { city: '경기', name: '시흥시', fullName: '경기도 시흥시', code: 149 },
      {
        city: '경기',
        name: '안산시 단원구',
        fullName: '경기도 안산시 단원구',
        code: 150,
      },
      {
        city: '경기',
        name: '안산시 상록구',
        fullName: '경기도 안산시 상록구',
        code: 151,
      },
      { city: '경기', name: '안성시', fullName: '경기도 안성시', code: 152 },
      {
        city: '경기',
        name: '안양시 동안구',
        fullName: '경기도 안양시 동안구',
        code: 153,
      },
      {
        city: '경기',
        name: '안양시 만안구',
        fullName: '경기도 안양시 만안구',
        code: 154,
      },
      { city: '경기', name: '양주시', fullName: '경기도 양주시', code: 155 },
      { city: '경기', name: '양평군', fullName: '경기도 양평군', code: 156 },
      { city: '경기', name: '여주시', fullName: '경기도 여주시', code: 157 },
      { city: '경기', name: '연천군', fullName: '경기도 연천군', code: 158 },
      { city: '경기', name: '오산시', fullName: '경기도 오산시', code: 159 },
      {
        city: '경기',
        name: '의정부시',
        fullName: '경기도 의정부시',
        code: 160,
      },
      { city: '경기', name: '이천시', fullName: '경기도 이천시', code: 161 },
      { city: '경기', name: '파주시', fullName: '경기도 파주시', code: 162 },
      { city: '경기', name: '평택시', fullName: '경기도 평택시', code: 163 },
      { city: '경기', name: '포천시', fullName: '경기도 포천시', code: 164 },
      { city: '경기', name: '하남시', fullName: '경기도 하남시', code: 165 },
      { city: '경기', name: '화성시', fullName: '경기도 화성시', code: 166 },
    ],
  },
  { city: '인천', name: '인천', fullName: '인천', code: 167 },
  { city: '대전', name: '대전', fullName: '대전', code: 168 },
  {
    city: '세종',
    name: '세종',
    fullName: '세종',
    code: 169,
  },
  {
    city: '충북',
    name: '충북',
    fullName: '충북',
    code: 170,
  },
  {
    city: '광주',
    name: '광주',
    fullName: '광주',
    code: 171,
  },
  {
    city: '전남',
    name: '전남',
    fullName: '전남',
    code: 172,
  },
  {
    city: '전북',
    name: '전북',
    fullName: '전북',
    code: 173,
  },
  {
    city: '대구',
    name: '대구',
    fullName: '대구',
    code: 174,
  },
  {
    city: '경북',
    name: '경북',
    fullName: '경북',
    code: 175,
  },
  {
    city: '부산',
    name: '부산',
    fullName: '부산',
    code: 176,
  },
  {
    city: '울산',
    name: '울산',
    fullName: '울산',
    code: 177,
  },
  {
    city: '경남',
    name: '경남',
    fullName: '경남',
    code: 178,
  },
  {
    city: '강원',
    name: '강원',
    fullName: '강원',
    code: 179,
  },
  {
    city: '제주',
    name: '제주',
    fullName: '제주',
    code: 180,
  },
];
