import clasLogo from '@/assets/images/logo/clas/clas_logo.png';

import {
  DOCS_EXTENSIONS,
  EXECUTABLE_EXTENSIONS,
  IMAGE_EXTENSIONS,
  MEDIA_EXTENSIONS,
  VOICE_EXTENSIONS,
  ZIP_EXTENSIONS,
} from '../constants/file';

export const config_clas_admin = {
  Type: 'clas_admin',
  HomeType: {
    homeShape: 'home',
    homeLogo: clasLogo,
    homeBackgroundColor: '#F9FAFB',
  },
  MainColor: '#3F83F8',
  HeaderStyle: {
    BackgroundColor: '#FAFCFF',
    MemberCountColor: '#9AA0A6',
  },
  BodyColor: '#EBF5FF',
  IconColor: '',
  CheckColor: '#3F83F8',
  PaginationColor: '',
  FloatingButtonBackgroundColor: '#FFFFFF',
  FloatingButtonColor: '#232D3B',
  ButtonPrimaryColor: '#3F83F8',
  MefillColor: '',
  AutoMessageBackgroundColor: '#FFFFFF99',
  AutoMessageTextColor: '#232D3B',
  ToastBackgroundColor: '',
  FirstRankColor: '#FF4A3F',
  MessageMenu: ['reply', 'reaction', 'copy', 'delete'],
  MessageMenuStyle: {
    BackgroundColor: 'transparent',
    IconColor: '#6B6B6B',
  },
  MessageDeliverText: '전달',
  HighlightedFocusedMessageColor: '#011B6B',
  HighlightedOtherMessageColor: '#7585B9',
  HighlightedTextColor: '#FFFFFF',
  MessageTitleColor: '',
  MyMessageStyle: {
    BackgroundColor: '#3F83F8',
    TextColor: '#FFFFFF',
    LinkColor: '#FFFFFF',
    MentionColor: '#FFFFFF',
    OgLinkColor: '',
    DeletedMessageColor: '#9AA0A6',
    ReplyArrowColor: 'rgba(255, 255, 255, 0.4)',
    ReplyNameColor: '#FFFFFF',
    ReplyToColor: 'rgba(255, 255, 255, 0.8)',
    ReplyMessageColor: 'rgba(255, 255, 255, 0.4)',
  },
  OtherMessageStyle: {
    BackgroundColor: '#FFFFFF',
    TextColor: '#202124',
    LinkColor: '#3F83F8',
    MentionColor: '#202124',
    OgLinkColor: '',
    DeletedMessageColor: '#9AA0A6',
    ReplyArrowColor: '#5C80FF',
    ReplyNameColor: '',
    ReplyToColor: '',
    ReplyMessageColor: '',
  },
  InputMessageStyle: {
    ReplyNameColor: '',
    ReplyToColor: '',
    ReplyArrowColor: '',
    BackGroundColor: '#F9FAFB',
  },
  SearchBarStyle: {
    BackgroundColor: '#FFFFFF',
    BorderColor: '#3F83F8',
    Collapse: true,
    Width: null as null | number,
  },
  ReactionChipStyle: {
    BorderColor: '#4260FF',
    BackgroundColor: '#E4EAFF',
  },
  FooterType: 'Default',
  AppBarType: 'custom',
  MentionType: 'None',
  MsgMenuType: '',
  MsgDeliverTabType: ['persona', 'room'],
  BottomItemsType: {
    Album: true,
    Camera: true,
    Drive: false,
    Drawer: false,
    File: true,
    Notice: true,
    Vote: true,
    Mail: true,
    Contact: false,
    Reserve: false,
  },
  FeatureNameType: {
    Room: '룸',
    Talk: '톡',
    RoomExit:
      '룸의 모든 데이터에 접근할 수 없게 됩니다.\n중요한 데이터는 미리 백업해 두세요.',
    RoomExitDesc: '',
    DmRoomExitButton: '',
    MiniChat: '',
  },
  FooterMenuItems: {
    Mail: false,
    Emoticon: true,
    Vote: false,
    Notice: false,
    File: true,
    Reserve: false,
    Editor: false,
  },
  RoomMenuItemsType: {
    RoomLeaderRoomDelete: false,
    MemberInvite: true,
    DMMemberInvite: false,
    InviteURLCopy: false,
    File: true,
    Link: true,
    Meeting: false,
    RoomMenuFooterExit: true,
    RoomSetting: true,
    Pin: true,
  },
  RoomList: {
    Title: '상담톡',
    RoomAlias: '',
    ShowProfile: false,
    ShowCreateRoomButton: false,
    SearchRoom: {
      ShowButton: false,
      ButtonIcon: undefined,
    },
    RoomTypeIds: {
      RoomList: [1, 4],
      CreateRoom: undefined,
    },
  },
  HeaderMenuTitle: 'Talk 게시판',
  HeaderMenuAppsTitle: '',
  HeaderMenuItems: {
    DateSearch: false,
    Drawer: false,
    Drive: false,
    Calendar: false,
    Meeting: true,
    MiniChat: false,
    KeywordSearch: true,
    RoomMenu: false,
  },
  ShowHeaderItemName: false,
  roomEnter: {
    common: false,
    dmRoom: false,
  },
  hasMyRoom: false,
  CanDeleteEditContents: {
    Delete: {
      RoomLeader: false,
      Admin: false,
    },
    Edit: {
      RoomLeader: false,
      Admin: false,
    },
  },
  DialogHeaderStyle: {
    Icon: false,
    Background: false,
  },
  ProfileDialog: {
    Visible: false,
    MessageButton: false,
  },
  SupportedExtensions: [...IMAGE_EXTENSIONS],
  UnsupportedExtensions: [
    ...MEDIA_EXTENSIONS,
    ...VOICE_EXTENSIONS,
    ...DOCS_EXTENSIONS,
    ...ZIP_EXTENSIONS,
    ...EXECUTABLE_EXTENSIONS,
  ],
  ShowRoomTypeIcon: {
    Open: false,
  },
  MeetingAvailableRoomTypeNames: ['1:1'],
  ShowRecentEmoticons: true,
  MemberSelectorSearchKeys: undefined,
  AppNames: {
    File: '첨부함',
    Drive: '드라이브',
    Calendar: '캘린더',
    Meeting: '미팅',
  },
  FileOpenType: undefined,
};
