import { FileOpenType } from '@/@types';
import ChatSearchLine from '@/assets/icons/ChatSearchLine.svg';

import {
  DOCS_EXTENSIONS,
  EXECUTABLE_EXTENSIONS,
  IMAGE_EXTENSIONS,
  MEDIA_EXTENSIONS,
  VOICE_EXTENSIONS,
  ZIP_EXTENSIONS,
} from '../constants/file';

export const config_ekr = {
  Type: 'ekr',
  HomeType: { homeShape: 'my', homeLogo: '', homeBackgroundColor: '' },
  MainColor: '#3663F6',
  HeaderStyle: {
    BackgroundColor: '#FAFCFF',
    MemberCountColor: '#9AA0A6',
  },
  BodyColor: '#E8EFFA',
  IconColor: '',
  CheckColor: '#3663F6',
  PaginationColor: '',
  FloatingButtonBackgroundColor: '#FFFFFF',
  FloatingButtonColor: '#202124',
  ButtonPrimaryColor: '#3663F6',
  MefillColor: '#3663F6',
  AutoMessageBackgroundColor: 'rgba(255, 255, 255, 0.6)',
  AutoMessageTextColor: '#202124',
  ToastBackgroundColor: '#202124',
  FirstRankColor: '#3663F6',
  MessageMenu: [
    'reply',
    'reaction',
    'copy',
    'unreadUser',
    'delete',
    'notice',
    'deliver',
  ],
  MessageMenuStyle: {
    BackgroundColor: '',
    IconColor: '',
  },
  MessageDeliverText: '전달',
  HighlightedFocusedMessageColor: '#011B6B',
  HighlightedOtherMessageColor: '#7585B9',
  HighlightedTextColor: '#FFFFFF',
  MessageTitleColor: '#3663F6',
  MyMessageStyle: {
    BackgroundColor: '#3663F6',
    TextColor: '#FFFFFF',
    LinkColor: '#FFFFFF',
    MentionColor: '#FFFFFF',
    OgLinkColor: '',
    DeletedMessageColor: '#FFFFFF',
    ReplyArrowColor: '#FFFFFF',
    ReplyNameColor: '#FFFFFF',
    ReplyToColor: '#FFFFFF',
    ReplyMessageColor: 'rgba(255, 255, 255, 0.4)',
  },
  OtherMessageStyle: {
    BackgroundColor: '#FFFFFF',
    TextColor: '#202124',
    LinkColor: '#3663F6',
    MentionColor: '#3663F6',
    OgLinkColor: '',
    DeletedMessageColor: 'rgba(32, 33, 36, 0.4)',
    ReplyArrowColor: '#5C80FF',
    ReplyNameColor: 'rgba(32, 33, 36, 0.8)',
    ReplyToColor: 'rgba(32, 33, 36, 0.4)',
    ReplyMessageColor: '#202124',
  },
  InputMessageStyle: {
    ReplyNameColor: '',
    ReplyToColor: '',
    ReplyArrowColor: '',
    BackGroundColor: '',
  },
  SearchBarStyle: {
    BackgroundColor: '#FFFFFF',
    BorderColor: '#3663F6',
    Collapse: true,
    Width: null as null | number,
  },
  ReactionChipStyle: {
    BorderColor: '',
    BackgroundColor: '',
  },
  FooterType: 'Default',
  AppBarType: 'custom',
  MentionType: 'List',
  MsgMenuType: '',
  MsgDeliverTabType: ['org', 'room'],
  BottomItemsType: {
    Album: true,
    Camera: true,
    Drive: true,
    Drawer: true,
    File: true,
    Notice: true,
    Vote: true,
    Mail: false,
    Contact: false,
    Reserve: false,
  },
  FeatureNameType: {
    Room: '룸',
    Talk: '톡',
    RoomExit:
      '룸의 멤버가 아니라면, 다른 앱에서도\n 해당 룸의 데이터에 접근할 수 없습니다.',
    RoomExitDesc: '',
    DmRoomExitButton: '채팅 닫기',
    MiniChat: '미니 채팅',
  },
  FooterMenuItems: {
    Mail: false,
    Emoticon: true,
    Vote: true,
    Notice: true,
    File: true,
    Reserve: false,
    Editor: false,
  },
  RoomMenuItemsType: {
    RoomLeaderRoomDelete: false,
    MemberInvite: true,
    DMMemberInvite: true,
    InviteURLCopy: true,
    File: true,
    Link: false,
    Meeting: true,
    RoomMenuFooterExit: true,
    RoomSetting: true,
    Pin: true,
  },
  RoomList: {
    Title: '톡톡',
    RoomAlias: '채팅',
    ShowProfile: true,
    ShowCreateRoomButton: true,
    SearchRoom: {
      ShowButton: true,
      ButtonIcon: ChatSearchLine,
    },
    RoomTypeIds: {
      RoomList: [1, 5, 7, 9, 11],
      CreateRoom: [5, 7, 9],
    },
  },
  HeaderMenuTitle: '게시판',
  HeaderMenuAppsTitle: '앱 연동',
  HeaderMenuItems: {
    DateSearch: false,
    Drawer: true,
    Drive: true,
    Calendar: true,
    Meeting: true,
    MiniChat: false,
    KeywordSearch: true,
    RoomMenu: true,
  },
  ShowHeaderItemName: true,
  roomEnter: {
    common: false,
    dmRoom: true,
  },
  hasMyRoom: true,
  CanDeleteEditContents: {
    Delete: {
      RoomLeader: false,
      Admin: false,
    },
    Edit: {
      RoomLeader: false,
      Admin: false,
    },
  },
  DialogHeaderStyle: {
    Icon: false,
    Background: false,
  },
  ProfileDialog: {
    Visible: true,
    MessageButton: false,
  },
  SupportedExtensions: [
    ...IMAGE_EXTENSIONS,
    ...MEDIA_EXTENSIONS,
    ...VOICE_EXTENSIONS,
    ...DOCS_EXTENSIONS,
    ...ZIP_EXTENSIONS,
  ],
  UnsupportedExtensions: [...EXECUTABLE_EXTENSIONS],
  ShowRoomTypeIcon: {
    Open: true,
  },
  MeetingAvailableRoomTypeNames: ['일반'],
  ShowRecentEmoticons: true,
  MemberSelectorSearchKeys: undefined,
  AppNames: {
    File: '첨부파일',
    Drive: '공유문서',
    Calendar: '일정관리',
    Meeting: '화상회의',
  },
  FileOpenType: FileOpenType.SUBAPP,
};
