import foodistMainLogo from '@/assets/images/logo/foodist/foodist_main_logo.png';

import {
  DOCS_EXTENSIONS,
  EXECUTABLE_EXTENSIONS,
  IMAGE_EXTENSIONS,
  MEDIA_EXTENSIONS,
  VOICE_EXTENSIONS,
  ZIP_EXTENSIONS,
} from '../constants/file';

export const config_foodist = {
  Type: 'foodist',
  HomeType: {
    homeShape: 'home',
    homeLogo: foodistMainLogo,
    homeBackgroundColor: '',
  },
  MainColor: '#FB4516',
  HeaderStyle: {
    BackgroundColor: '#F8F9FA',
    MemberCountColor: '#FB4516',
  },
  BodyColor: '#E8EAED',
  IconColor: '#FB4516',
  CheckColor: '#95C11F',
  PaginationColor: '#FF6F0F',
  FloatingButtonBackgroundColor: '#00CB76',
  FloatingButtonColor: '#FFFFFF',
  ButtonPrimaryColor: '#000000',
  MefillColor: '',
  AutoMessageBackgroundColor: '#FFFFFF',
  AutoMessageTextColor: '#5F6368',
  ToastBackgroundColor: '',
  FirstRankColor: '#FF4A3F',
  MessageMenu: [
    'reply',
    'reaction',
    'copy',
    'delete',
    'blind',
    'report',
    'notice',
    'deliver',
  ],
  MessageMenuStyle: {
    BackgroundColor: '',
    IconColor: '',
  },
  MessageDeliverText: '다른 방으로 전달',
  HighlightedFocusedMessageColor: '',
  HighlightedOtherMessageColor: '',
  HighlightedTextColor: '',
  MessageTitleColor: '',
  MyMessageStyle: {
    BackgroundColor: '#FF6F0F',
    TextColor: '#FFFFFF',
    LinkColor: '#F1F3F4',
    MentionColor: '#FFFFFF',
    OgLinkColor: '#FB4516',
    DeletedMessageColor: '#E8EAED',
    ReplyArrowColor: '#202124',
    ReplyNameColor: '#FFFFFF',
    ReplyToColor: '#FFFFFF',
    ReplyMessageColor: '#F1F3F4',
  },
  OtherMessageStyle: {
    BackgroundColor: '#FFFFFF',
    TextColor: '#202124',
    LinkColor: '#202124',
    MentionColor: '#202124',
    OgLinkColor: '#FB4516',
    DeletedMessageColor: '#202124',
    ReplyArrowColor: '#FB4516',
    ReplyNameColor: '#FB4516',
    ReplyToColor: '#FB4516',
    ReplyMessageColor: '#3C4043',
  },
  InputMessageStyle: {
    ReplyNameColor: '#FB4516',
    ReplyToColor: '#80868B',
    ReplyArrowColor: '#FB4516',
    BackGroundColor: '',
  },
  SearchBarStyle: {
    BackgroundColor: '',
    BorderColor: '',
    Collapse: true,
    Width: null as null | number,
  },
  ReactionChipStyle: {
    BorderColor: '#FB4516',
    BackgroundColor: '#FFE2CF',
  },
  FooterType: 'Large',
  AppBarType: 'AuthenticationAppBar',
  MentionType: 'Search',
  MsgMenuType: '',
  MsgDeliverTabType: ['room'],
  BottomItemsType: {
    Album: true,
    Camera: true,
    Drive: false,
    Drawer: false,
    File: true,
    Notice: false,
    Vote: false,
    Mail: false,
    Contact: false,
    Reserve: false,
  },
  FeatureNameType: {
    Room: '방',
    Talk: '대화방',
    RoomExit: '대화방을 나가시겠습니까?\n',
    RoomExitDesc: '이전 대화내역이 모두 삭제됩니다.',
    DmRoomExitButton: '나가기',
    MiniChat: '',
  },
  FooterMenuItems: {
    Mail: false,
    Emoticon: true,
    Vote: true,
    Notice: true,
    File: true,
    Reserve: false,
    Editor: false,
  },
  RoomMenuItemsType: {
    RoomLeaderRoomDelete: true,
    MemberInvite: false,
    DMMemberInvite: false,
    InviteURLCopy: true,
    File: true,
    Link: true,
    Meeting: false,
    RoomMenuFooterExit: true,
    RoomSetting: true,
    Pin: true,
  },
  RoomList: {
    Title: '톡',
    RoomAlias: '',
    ShowProfile: true,
    ShowCreateRoomButton: true,
    SearchRoom: {
      ShowButton: false,
      ButtonIcon: undefined,
    },
    RoomTypeIds: {
      RoomList: [],
      CreateRoom: undefined,
    },
  },
  HeaderMenuTitle: '게시판',
  HeaderMenuAppsTitle: '첨부함',
  HeaderMenuItems: {
    DateSearch: true,
    Drawer: false,
    Drive: false,
    Calendar: false,
    Meeting: false,
    MiniChat: false,
    KeywordSearch: true,
    RoomMenu: true,
  },
  ShowHeaderItemName: false,
  roomEnter: {
    common: true,
    dmRoom: true,
  },
  hasMyRoom: true,
  CanDeleteEditContents: {
    Delete: {
      RoomLeader: true,
      Admin: true,
    },
    Edit: {
      RoomLeader: false,
      Admin: true,
    },
  },
  DialogHeaderStyle: {
    Icon: false,
    Background: false,
  },
  ProfileDialog: {
    Visible: true,
    MessageButton: false,
  },
  SupportedExtensions: [
    ...IMAGE_EXTENSIONS,
    ...MEDIA_EXTENSIONS,
    ...VOICE_EXTENSIONS,
    ...DOCS_EXTENSIONS,
    ...ZIP_EXTENSIONS,
  ],
  UnsupportedExtensions: [...EXECUTABLE_EXTENSIONS],
  ShowRoomTypeIcon: {
    Open: false,
  },
  MeetingAvailableRoomTypeNames: [],
  ShowRecentEmoticons: true,
  MemberSelectorSearchKeys: undefined,
  AppNames: {
    File: '첨부함',
    Drive: '드라이브',
    Calendar: '캘린더',
    Meeting: '미팅',
  },
  FileOpenType: undefined,
};
