import { Icon } from '@wapl/ui';

import senLogo from '@/assets/images/logo/sen/sen-logo.png';
import * as T from '@types';
import { FileOpenType } from '@types';

import {
  DOCS_EXTENSIONS,
  EXECUTABLE_EXTENSIONS,
  IMAGE_EXTENSIONS,
  MEDIA_EXTENSIONS,
  VOICE_EXTENSIONS,
  ZIP_EXTENSIONS,
} from '../constants/file';

export const config_sen = {
  Type: 'sen',
  HomeType: {
    homeShape: 'my',
    homeLogo: senLogo,
    homeBackgroundColor: '',
  },
  MainColor: '#5782F6',
  HeaderStyle: {
    BackgroundColor: '#DDE5EF',
    MemberCountColor: '#9AA0A6',
  },
  BodyColor: '#E9EFF7',
  IconColor: '#202124',
  CheckColor: '#5782F6',
  PaginationColor: '#5782F6',
  FloatingButtonBackgroundColor: '#FFFFFF',
  FloatingButtonColor: '#202124',
  ButtonPrimaryColor: '#5782F6',
  MefillColor: '#5782F6',
  AutoMessageBackgroundColor: '#F4F7FC',
  AutoMessageTextColor: '#3C4043',
  ToastBackgroundColor: '#3C4043',
  FirstRankColor: '#5782F6',
  MessageMenu: [
    'reply',
    'reaction',
    'copy',
    'unreadUser',
    'delete',
    'notice',
    'deliver',
  ],
  MessageMenuStyle: {
    BackgroundColor: '',
    IconColor: '',
  },
  HighlightedFocusedMessageColor: '#011B6B',
  HighlightedOtherMessageColor: '#7585B9',
  HighlightedTextColor: '#FFFFFF',
  MessageTitleColor: '#5782F6',
  MyMessageStyle: {
    BackgroundColor: '#C5DAF9',
    TextColor: '#202124',
    LinkColor: '#067DFD',
    MentionColor: '#5782F6',
    OgLinkColor: '#202124',
    DeletedMessageColor: 'rgba(0, 0, 0, 0.5)',
    ReplyArrowColor: '#5782F6',
    ReplyNameColor: '#202124',
    ReplyToColor: 'rgba(32, 33, 36, 0.8)',
    ReplyMessageColor: 'rgba(32, 33, 36, 0.4)',
  },
  MessageDeliverText: '전달',
  OtherMessageStyle: {
    BackgroundColor: '#FFFFFF',
    TextColor: '#202124',
    LinkColor: '#067DFD',
    MentionColor: '#5782F6',
    OgLinkColor: '#202124',
    DeletedMessageColor: 'rgba(32, 33, 36, 0.4)',
    ReplyArrowColor: 'rgba(0, 0, 0, 0.4)',
    ReplyNameColor: 'rgba(32, 33, 36, 0.8)',
    ReplyToColor: 'rgba(0, 0, 0, 0.4)',
    ReplyMessageColor: 'rgba(32, 33, 36, 0.4)',
  },
  InputMessageStyle: {
    ReplyNameColor: '#5782F6',
    ReplyToColor: '#202124',
    ReplyArrowColor: '#5782F6',
    BackGroundColor: '#f5f7f9',
  },
  SearchBarStyle: {
    BackgroundColor: '#F5F7F9',
    BorderColor: 'transparent',
    Collapse: true,
    Width: null as null | number,
  },
  ReactionChipStyle: {
    BorderColor: '',
    BackgroundColor: '',
  },
  FooterType: 'Default',
  AppBarType: 'custom',
  MentionType: 'List',
  MsgMenuType: '',
  MsgDeliverTabType: ['favorite', 'org', 'room'],
  BottomItemsType: {
    Album: true,
    Camera: true,
    Drive: false,
    Drawer: false,
    File: true,
    Notice: false,
    Vote: false,
    Mail: false,
    Contact: false,
    Reserve: false,
  },
  FeatureNameType: {
    Room: '대화방',
    Talk: '대화',
    RoomExit:
      '대화방의 멤버가 아니라면, 다른 앱에서도 해당 대화방의 데이터에 접근할 수 없습니다.',
    RoomExitDesc: '',
    DmRoomExitButton: '대화 닫기',
    MiniChat: '미니 대화',
  },
  FooterMenuItems: {
    Mail: false,
    Emoticon: true,
    Vote: true,
    Notice: true,
    File: true,
    Reserve: false,
    Editor: true,
  },
  RoomMenuItemsType: {
    RoomLeaderRoomDelete: false,
    MemberInvite: true,
    DMMemberInvite: false,
    InviteURLCopy: true,
    File: false,
    Link: false,
    Meeting: false,
    RoomMenuFooterExit: true,
    RoomSetting: false,
    Pin: true,
  },
  RoomList: {
    Title: '대화방',
    RoomAlias: '',
    ShowProfile: true,
    ShowCreateRoomButton: true,
    SearchRoom: {
      ShowButton: true,
      ButtonIcon: Icon.ChatOpenLine,
    },
    RoomTypeIds: {
      RoomList: [-2, 1, 2, 3, 4],
      CreateRoom: [2, 3, 4],
    },
  },
  HeaderMenuTitle: '게시판',
  HeaderMenuAppsTitle: '앱 연동',
  HeaderMenuItems: {
    DateSearch: false,
    Drawer: true,
    Drive: true,
    Calendar: true,
    Meeting: true,
    MiniChat: true,
    KeywordSearch: true,
    RoomMenu: true,
  },
  ShowHeaderItemName: false,
  roomEnter: {
    common: false,
    dmRoom: true,
  },
  hasMyRoom: true,
  CanDeleteEditContents: {
    Delete: {
      RoomLeader: false,
      Admin: false,
    },
    Edit: {
      RoomLeader: false,
      Admin: false,
    },
  },
  DialogHeaderStyle: {
    Icon: false,
    Background: false,
  },
  ProfileDialog: {
    Visible: true,
    MessageButton: true,
  },
  SupportedExtensions: [
    ...IMAGE_EXTENSIONS,
    ...MEDIA_EXTENSIONS,
    ...VOICE_EXTENSIONS,
    ...DOCS_EXTENSIONS,
    ...ZIP_EXTENSIONS,
  ],
  UnsupportedExtensions: [...EXECUTABLE_EXTENSIONS],
  ShowRoomTypeIcon: {
    Open: false,
  },
  MeetingAvailableRoomTypeNames: ['일반', '조직', '1:1', '오픈'],
  ShowRecentEmoticons: false,
  MemberSelectorSearchKeys: [
    'name',
    'orgName',
    'positionName',
  ] as T.MemberSelectorSearchType[],
  AppNames: {
    File: '첨부함',
    Drive: '드라이브',
    Calendar: '캘린더',
    Meeting: '미팅',
  },
  FileOpenType: FileOpenType.HANCOMOFFICE,
};
