import { FileOpenType } from '@/@types';
import ChatSearchLine from '@/assets/icons/ChatSearchLine.svg';

import {
  DOCS_EXTENSIONS,
  EXECUTABLE_EXTENSIONS,
  IMAGE_EXTENSIONS,
  MEDIA_EXTENSIONS,
  VOICE_EXTENSIONS,
  ZIP_EXTENSIONS,
} from '../constants/file';

export const config_superapp = {
  Type: 'superApp',
  HomeType: {
    homeShape: 'my',
    homeLogo: '',
    homeBackgroundColor: '',
  },
  MainColor: '#5558C9',
  HeaderStyle: {
    BackgroundColor: '#DEE4E9',
    MemberCountColor: '#9AA0A6',
  },
  BodyColor: '#E8ECEF',
  IconColor: '',
  CheckColor: '#5558C9',
  PaginationColor: '',
  FloatingButtonBackgroundColor: '#5558C9',
  FloatingButtonColor: '#FFFFFF',
  ButtonPrimaryColor: '#2C2D49',
  MefillColor: '',
  AutoMessageBackgroundColor: '#DEE4E9',
  AutoMessageTextColor: '#202124',
  ToastBackgroundColor: 'rgba(0, 0, 0, 0.7)',
  FirstRankColor: '#FF4A3F',
  MessageMenu: [
    'reply',
    'reaction',
    'copy',
    'unreadUser',
    'delete',
    'report',
    'notice',
    'deliver',
  ],
  MessageMenuStyle: {
    BackgroundColor: '',
    IconColor: '',
  },
  MessageDeliverText: '전달',
  HighlightedFocusedMessageColor: '#FFD03A',
  HighlightedOtherMessageColor: '#F9E39D',
  HighlightedTextColor: '#000000',
  MessageTitleColor: '',
  MyMessageStyle: {
    BackgroundColor: '#CADAF0',
    TextColor: '#202124',
    LinkColor: '#067DFD',
    MentionColor: '#5558C9',
    OgLinkColor: '',
    DeletedMessageColor: '#9AA0A6',
    ReplyArrowColor: '#5C80FF',
    ReplyNameColor: '',
    ReplyToColor: '',
    ReplyMessageColor: '',
  },
  OtherMessageStyle: {
    BackgroundColor: '#FFFFFF',
    TextColor: '#202124',
    LinkColor: '#067DFD',
    MentionColor: '#5558C9',
    OgLinkColor: '',
    DeletedMessageColor: '#9AA0A6',
    ReplyArrowColor: '#5C80FF',
    ReplyNameColor: '',
    ReplyToColor: '',
    ReplyMessageColor: '',
  },
  InputMessageStyle: {
    ReplyNameColor: '',
    ReplyToColor: '',
    ReplyArrowColor: '',
    BackGroundColor: '',
  },
  SearchBarStyle: {
    BackgroundColor: '',
    BorderColor: '',
    Collapse: true,
    Width: null as null | number,
  },
  ReactionChipStyle: {
    BorderColor: '',
    BackgroundColor: '',
  },
  FooterType: 'Default',
  AppBarType: 'custom',
  MentionType: 'Search',
  MsgMenuType: '',
  MsgDeliverTabType: ['persona', 'room'],
  BottomItemsType: {
    Album: true,
    Camera: true,
    Drive: false,
    Drawer: false,
    File: true,
    Notice: true,
    Vote: true,
    Mail: true,
    Contact: true,
    Reserve: true,
  },
  FeatureNameType: {
    Room: '룸',
    Talk: '톡',
    RoomExit:
      '룸의 모든 데이터에 접근할 수 없게 됩니다.\n중요한 데이터는 미리 백업해 두세요.',
    RoomExitDesc: '',
    DmRoomExitButton: '나가기',
    MiniChat: '미니 채팅',
  },
  FooterMenuItems: {
    Mail: true,
    Emoticon: true,
    Vote: true,
    Notice: true,
    File: true,
    Reserve: true,
    Editor: false,
  },
  RoomMenuItemsType: {
    RoomLeaderRoomDelete: false,
    MemberInvite: true,
    DMMemberInvite: false,
    InviteURLCopy: false,
    File: true,
    Link: true,
    Mail: true,
    Meeting: false,
    RoomMenuFooterExit: true,
    RoomSetting: true,
    Pin: true,
  },
  RoomList: {
    Title: '톡',
    RoomAlias: '',
    ShowProfile: true,
    ShowCreateRoomButton: true,
    SearchRoom: {
      ShowButton: true,
      ButtonIcon: ChatSearchLine,
    },
    RoomTypeIds: {
      RoomList: [],
      CreateRoom: undefined,
    },
  },
  HeaderMenuTitle: 'Talk 게시판',
  HeaderMenuAppsTitle: '첨부함',
  HeaderMenuItems: {
    DateSearch: false,
    Drawer: false,
    Drive: false,
    Calendar: false,
    Meeting: false,
    MiniChat: true,
    KeywordSearch: true,
    RoomMenu: true,
  },
  ShowHeaderItemName: false,
  roomEnter: {
    common: false,
    dmRoom: false,
  },
  hasMyRoom: true,
  CanDeleteEditContents: {
    Delete: {
      RoomLeader: false,
      Admin: false,
    },
    Edit: {
      RoomLeader: false,
      Admin: false,
    },
  },
  DialogHeaderStyle: {
    Icon: false,
    Background: false,
  },
  ProfileDialog: {
    Visible: true,
    MessageButton: false,
  },
  SupportedExtensions: [
    ...IMAGE_EXTENSIONS,
    ...MEDIA_EXTENSIONS,
    ...VOICE_EXTENSIONS,
    ...DOCS_EXTENSIONS,
    ...ZIP_EXTENSIONS,
  ],
  UnsupportedExtensions: [...EXECUTABLE_EXTENSIONS],
  ShowRoomTypeIcon: {
    Open: false,
  },
  MeetingAvailableRoomTypeNames: [],
  ShowRecentEmoticons: true,
  MemberSelectorSearchKeys: undefined,
  AppNames: {
    File: '첨부함',
    Drive: '드라이브',
    Calendar: '캘린더',
    Meeting: '미팅',
  },
  FileOpenType: FileOpenType.SUBAPP,
};
